{% set name = "xmlplot" %}
{% set version = "0.9.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xmlplot-{{ version }}.tar.gz
  sha256: 8635bb967a18035abd0e186f449ec56f17adfc75159b6e2f4222f29138bde814

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - xmlstore >=0.9.13

test:
  imports:
    - xmlplot
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BoldingBruggeman/xmlplot
  summary: 'Python package for coordinate-aware data reading and plotting'
  description: |
    xmlplot is a Python package for coordinate-aware reading and plotting
    of data in text and NetCDF format, using xml to store plot settings
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
